### ISSUE TITLE
Remove "title" of all entries in OPML

### ISSUE THREAD

**Issue by i2** [imdj/opml-editor#5]
Hi,

The "text" and "title" fields for some of the feeds in my OPML differ and I would like to just keep the former. Could you add a feature to delete `title="XYZ"` from all entries?

Thanks!

**Comment by i2** [comment]
Similar request could be to remove `htmlUrl="XYZ"` (which I believe is unnecessary). This will minimize OPML files that can otherwise get bloated and make managing them easier!

**Comment by imdj** [comment]
Hi,
Nice idea. Will work on it later towards the weekend and maybe set the foundation for a more generalized solution to delete, filter, etc.

**Comment by imdj** [comment]
This feature is now available under the name "Toggle attributes" in the edit menu.
You can uncheck the attributes you'd like to remove completely from all instances.

**Comment by i2** [comment]
Thanks!

One tiny point that I preferred to ask here instead of opening a new thread:
Right now, when doing anything on OPML, it adds the ending </outline> to each feed, i.e. it converts:
`<outline text="XYZ" xmlUrl="XYZ"/>` to `<outline text="XYZ" xmlUrl="XYZ"></outline>`

In the spirit of minimalization, can it not do that?

**Comment by imdj** [comment]
> it converts: `<outline text="XYZ" xmlUrl="XYZ"/>` to `<outline text="XYZ" xmlUrl="XYZ"></outline>`
> 
> In the spirit of minimalization, can it not do that?

I think we might need a preferences page where stuff like this can be toggled it as an option. I'll add it to the backlog but no promises. If you find more use cases for preferences please share them.

Thank you @i2 for sharing your experience and suggestions so I know where it can be improved.
